### ISSUE TITLE
The scripts might want to give the user a heads up if there's an authorization issue

### ISSUE THREAD

**Issue by imrehg** [resin-io-playground/staged-releases#15]
The current scripts are simple and readable, and that's great that way. 

When a user hits an authorization issue (e.g. expired token), then it just fails with not very clear error. I'm wondering if there was a way to handle that instead of e.g trying to debug a "parse error: Invalid numeric literal at EOF at line 1, column 12" error.

It's mostly a nice-to-have, if there's any idea, based on feedback.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7b15)

**Comment by thgreasi** [comment]
Resolved by #17
